export const PRODUCT = {
  id: 'aura-amber-cognac',
  name: 'AURA — Cognac Amber Quartz',
  tagline: 'Pure form. Refined flow.',
  description:
    'A single, hand-finished vessel in flame-polished amber borosilicate glass, closed with a knurled champagne-brass cap. AURA is designed to bring deep serenity to daily ritual.',
  image: '/assets/aura-bottle.jpg',
  sizes: [
    { id: '500', label: '500ml', sub: 'Everyday', price: 78 },
    { id: '750', label: '750ml', sub: 'Studio', price: 88 },
    { id: '1000', label: '1L', sub: 'Reserve', price: 104 },
  ],
  finishes: [
    { id: 'champagne', label: 'Brushed Brass', hex: '#c9a876', filter: 'sepia(0.55) saturate(2.1) hue-rotate(-8deg) brightness(1.08)' },
    { id: 'onyx', label: 'Onyx Billet', hex: '#1c1c1e', filter: 'none' },
    { id: 'graphite', label: 'Gunmetal', hex: '#6b6b70', filter: 'grayscale(0.6) brightness(1.15)' },
  ],
  collection: [
    {
      id: 'amber',
      number: '01',
      name: 'AURA Cognac Nectar',
      subtitle: 'Warm Baltic Amber Glass · Brushed Brass Billet',
      tag: 'Signature Reserve',
      category: 'mineral',
      description: 'Deep warm Baltic cognac and honey tones infused with rare earth mineral oxides. Kiln-fired 24-karat gold silkscreen with a brushed champagne brass billet closure.',
      notes: 'Sun-Warmed Resin · Golden Honey · Wild Tonka',
      swatchHex: '#d9822b',
      accentHex: '#f5a742',
      glassColor: 0xffeedd,
      attenuationColor: 0xd97724,
      attenuationDistance: 2.6,
      liquidColor: 0x9e5210,
      liquidOpacity: 0.72,
      capColor: 0xd4a359,
      capMetalness: 0.94,
      capRoughness: 0.20,
      haloColor: 0xe89938,
      foilColor: '#ffffff',
      foilAccent: '#f5c062',
      price: 78,
    },
    {
      id: 'obsidian',
      number: '02',
      name: 'AURA Obsidian Smoke',
      subtitle: 'Volcanic Smoked Quartz · Gunmetal Billet',
      tag: 'Architectural Edition',
      category: 'smoked',
      description: 'Deep volcanic smoked quartz glass absorbing glare while revealing liquid silhouettes. Finished with a diamond-knurled gunmetal cap and brilliant platinum typography.',
      notes: 'Smoked Vetiver · Wet River Stone · Black Pepper',
      swatchHex: '#2b2d38',
      accentHex: '#5e657a',
      glassColor: 0xd0d5e0,
      attenuationColor: 0x32384a,
      attenuationDistance: 2.2,
      liquidColor: 0x1e2434,
      liquidOpacity: 0.78,
      capColor: 0x2e323e,
      capMetalness: 0.96,
      capRoughness: 0.18,
      haloColor: 0x5e688a,
      foilColor: '#ffffff',
      foilAccent: '#9aa5be',
      price: 84,
    },
    {
      id: 'emerald',
      number: '03',
      name: 'AURA Nordic Emerald',
      subtitle: 'Scandinavian Pine Glass · Moss Alloy',
      tag: 'Nordic Heritage',
      category: 'mineral',
      description: 'Inspired by ancient apothecary carboys and Danish coastal pine canopies. Hand-finished with a matte moss alloy cap and gilded brass typography.',
      notes: 'Fir Needle · Deep Pine · Coastal Rain Moss',
      swatchHex: '#1e4a38',
      accentHex: '#2d6e53',
      glassColor: 0xd6ede1,
      attenuationColor: 0x1f5c42,
      attenuationDistance: 2.4,
      liquidColor: 0x143c2c,
      liquidOpacity: 0.76,
      capColor: 0x3d5c4b,
      capMetalness: 0.92,
      capRoughness: 0.22,
      haloColor: 0x2e6b50,
      foilColor: '#ffffff',
      foilAccent: '#a8d8be',
      price: 88,
    },
    {
      id: 'cobalt',
      number: '04',
      name: 'AURA Cobalt Zenith',
      subtitle: 'Royal Sapphire Glass · Azure Titanium',
      tag: 'Oceanic Reserve',
      category: 'smoked',
      description: 'Deep royal sapphire crystal refracting oceanic indigo depths. Diamond-turned azure titanium closure with brilliant platinum silkscreen that catches grazing light.',
      notes: 'Sea Salt Spray · Arctic Kelp · Midnight Blue',
      swatchHex: '#162e4e',
      accentHex: '#2b588e',
      glassColor: 0xd8e6f8,
      attenuationColor: 0x1a467e,
      attenuationDistance: 2.3,
      liquidColor: 0x122846,
      liquidOpacity: 0.78,
      capColor: 0x23456e,
      capMetalness: 0.95,
      capRoughness: 0.18,
      haloColor: 0x2e62a4,
      foilColor: '#ffffff',
      foilAccent: '#7eb3f0',
      price: 92,
    },
    {
      id: 'rose',
      number: '05',
      name: 'AURA Rose Tourmaline',
      subtitle: 'Dusk Rose Quartz · Brushed Copper Billet',
      tag: 'Atelier Batch',
      category: 'mineral',
      description: 'Infused with mineral manganese and copper oxides during the melt, casting a radiant dusk blush through thick glass walls. Paired with an anodized copper-rose cap.',
      notes: 'Wild Briar · White Cedar · Warm Mineral Blush',
      swatchHex: '#9c4858',
      accentHex: '#c7687c',
      glassColor: 0xfde4ea,
      attenuationColor: 0xa84256,
      attenuationDistance: 2.5,
      liquidColor: 0x6e2634,
      liquidOpacity: 0.74,
      capColor: 0xb86c78,
      capMetalness: 0.90,
      capRoughness: 0.22,
      haloColor: 0xbf586c,
      foilColor: '#ffffff',
      foilAccent: '#f2a8b6',
      price: 82,
    },
    {
      id: 'terracotta',
      number: '06',
      name: 'AURA Terracotta Dune',
      subtitle: 'Smoked Desert Sienna · Burnished Bronze',
      tag: 'Earth & Clay Series',
      category: 'mineral',
      description: 'Rich earthen sienna and smoked copper oxides evoke Mediterranean desert dusk and terracotta kilns. Paired with burnished warm bronze and copper foil silkscreen.',
      notes: 'Sun-Baked Clay · Cardamom · Roasted Cedar',
      swatchHex: '#b8542b',
      accentHex: '#d86e3f',
      glassColor: 0xfde9de,
      attenuationColor: 0xb85028,
      attenuationDistance: 2.4,
      liquidColor: 0x7a3014,
      liquidOpacity: 0.76,
      capColor: 0x9b5434,
      capMetalness: 0.92,
      capRoughness: 0.22,
      haloColor: 0xc45c2c,
      foilColor: '#ffffff',
      foilAccent: '#f5986e',
      price: 82,
    },
    {
      id: 'amethyst',
      number: '07',
      name: 'AURA Amethyst Dusk',
      subtitle: 'Smoky Imperial Violet · Plum Alloy',
      tag: 'Twilight Batch',
      category: 'mineral',
      description: 'Twilight smoky violet borosilicate capturing dusk skies over Scandinavian fiords. Finished with an imperial plum alloy cap and silver-lilac silkscreen.',
      notes: 'Wild Black Currant · Night Iris · Smoky Cedar',
      swatchHex: '#4a2c54',
      accentHex: '#734682',
      glassColor: 0xf4e6fa,
      attenuationColor: 0x5a2d6b,
      attenuationDistance: 2.4,
      liquidColor: 0x3e184c,
      liquidOpacity: 0.78,
      capColor: 0x5a3866,
      capMetalness: 0.92,
      capRoughness: 0.20,
      haloColor: 0x763e8c,
      foilColor: '#ffffff',
      foilAccent: '#bfa0d8',
      price: 88,
    },
    {
      id: 'champagne',
      number: '08',
      name: 'AURA Champagne Atelier',
      subtitle: 'Aureolin Honey Crystal · Fluted 24k Gold',
      tag: 'Celebration Series',
      category: 'crystal',
      description: 'Luminous aureolin golden honey crystal refracting raking sunlight into effervescent caustics. Paired with a fluted champagne-gold cap and gilded specular typography.',
      notes: 'Golden Peach · Sunlit Citrus · Aged Brioche',
      swatchHex: '#c49a46',
      accentHex: '#e0b55a',
      glassColor: 0xfef7e8,
      attenuationColor: 0xb8892f,
      attenuationDistance: 2.8,
      liquidColor: 0x7e5814,
      liquidOpacity: 0.68,
      capColor: 0xcca04a,
      capMetalness: 0.96,
      capRoughness: 0.18,
      haloColor: 0xd9a842,
      foilColor: '#ffffff',
      foilAccent: '#ffd878',
      price: 86,
    },
    {
      id: 'glacier',
      number: '09',
      name: 'AURA Glacier Cyan',
      subtitle: 'Arctic Cyan Turquoise · Frost Silver Billet',
      tag: 'Alpine Expedition',
      category: 'crystal',
      description: 'Inspired by blue glacial ice sheets and alpine meltwater. Translucent deep aquamarine vessel paired with a frost-silver machined billet cap and crisp arctic typography.',
      notes: 'Alpine Snowmelt · Crisp Ozone · Crushed Mint',
      swatchHex: '#1b6b7a',
      accentHex: '#2b98ac',
      glassColor: 0xd8f5fc,
      attenuationColor: 0x1f7485,
      attenuationDistance: 2.6,
      liquidColor: 0x124752,
      liquidOpacity: 0.72,
      capColor: 0x6e8f96,
      capMetalness: 0.94,
      capRoughness: 0.18,
      haloColor: 0x2da8bf,
      foilColor: '#ffffff',
      foilAccent: '#7ae2f5',
      price: 82,
    },
    {
      id: 'noir',
      number: '10',
      name: 'AURA Eclipse Noir',
      subtitle: 'Monolithic Jet Glass · Triple PVD Carbon',
      tag: 'Monolith Edition',
      category: 'smoked',
      description: 'An enigmatic study in total optical absorption. Deep obsidian smoked glass paired with a triple-black diamond-like carbon cap and platinum silkscreen.',
      notes: 'Charcoal Smoke · Birch Tar · Black Obsidian',
      swatchHex: '#141418',
      accentHex: '#2e2e36',
      glassColor: 0xb5b7c0,
      attenuationColor: 0x1a1a20,
      attenuationDistance: 1.8,
      liquidColor: 0x0f0f14,
      liquidOpacity: 0.88,
      capColor: 0x161618,
      capMetalness: 0.98,
      capRoughness: 0.14,
      haloColor: 0x484856,
      foilColor: '#ffffff',
      foilAccent: '#8a8e9e',
      price: 96,
    },
    {
      id: 'jade',
      number: '11',
      name: 'AURA Imperial Jade',
      subtitle: 'Viridian Silk Glass · Patina Bronze Billet',
      tag: 'Dynastic Series',
      category: 'mineral',
      description: 'Deep imperial viridian jade crystal capturing deep spring forest moss and mineral reserves. Paired with a hand-patinated bronze closure and brilliant gold lettering.',
      notes: 'Crushed Jade · Wild Tea Leaf · Cedar Bark',
      swatchHex: '#1c523c',
      accentHex: '#2d8260',
      glassColor: 0xdcf2e8,
      attenuationColor: 0x18593e,
      attenuationDistance: 2.5,
      liquidColor: 0x0f3b28,
      liquidOpacity: 0.76,
      capColor: 0x4a6b5a,
      capMetalness: 0.92,
      capRoughness: 0.20,
      haloColor: 0x227854,
      foilColor: '#ffffff',
      foilAccent: '#7ef0be',
      price: 90,
    },
    {
      id: 'crimson',
      number: '12',
      name: 'AURA Solar Crimson',
      subtitle: 'Molten Ruby Glass · Burnished Copper Billet',
      tag: 'Solstice Series',
      category: 'mineral',
      description: 'Deep molten ruby crystal evocative of solstice twilight and volcanic magma. Refracts fiery garnet caustics, finished with burnished copper billet and gilded typography.',
      notes: 'Pomegranate Rind · Smoked Cedar · Solar Amber',
      swatchHex: '#6b1820',
      accentHex: '#9c2430',
      glassColor: 0xfad6da,
      attenuationColor: 0x781620,
      attenuationDistance: 2.3,
      liquidColor: 0x48080f,
      liquidOpacity: 0.82,
      capColor: 0x8a323a,
      capMetalness: 0.92,
      capRoughness: 0.20,
      haloColor: 0x9c202e,
      foilColor: '#ffffff',
      foilAccent: '#f58490',
      price: 94,
    },
  ],
};

// Aliases for compatibility
PRODUCT.variants = PRODUCT.collection;

const VARIANT_ALIASES = {
  original: 'amber',
  crystal: 'glacier',
  midnight: 'obsidian',
  pearl: 'champagne',
};

export function findSize(id) {
  return PRODUCT.sizes.find((s) => s.id === id) || PRODUCT.sizes[0];
}

export function findFinish(id) {
  return PRODUCT.finishes.find((f) => f.id === id) || PRODUCT.finishes[0];
}

export function findVariant(id) {
  const normalizedId = VARIANT_ALIASES[id] || id;
  return PRODUCT.collection.find((c) => c.id === normalizedId) || PRODUCT.collection[0];
}

