export const PRODUCT = {
  id: 'aura-original',
  name: 'AURA — The Original',
  tagline: 'Pure form. Refined flow.',
  description:
    'A single, hand-finished vessel in borosilicate glass, closed with a knurled aluminum cap. AURA is designed to disappear into daily ritual — an object built to be used, not displayed.',
  image: '/assets/aura-bottle.jpg',
  sizes: [
    { id: '500', label: '500ml', sub: 'Everyday', price: 68 },
    { id: '750', label: '750ml', sub: 'Studio', price: 78 },
    { id: '1000', label: '1L', sub: 'Reserve', price: 92 },
  ],
  finishes: [
    { id: 'onyx', label: 'Onyx', hex: '#1c1c1e', filter: 'none' },
    { id: 'champagne', label: 'Champagne', hex: '#c9a876', filter: 'sepia(0.55) saturate(2.1) hue-rotate(-8deg) brightness(1.08)' },
    { id: 'graphite', label: 'Graphite', hex: '#6b6b70', filter: 'grayscale(0.6) brightness(1.15)' },
  ],
  collection: [
    {
      id: 'original',
      name: 'AURA Original',
      subtitle: 'Clear Borosilicate',
      tag: 'Signature Edition',
      description: 'Ultra-pure fire-polished borosilicate crystal paired with a diamond-turned obsidian closure. High optical clarity with zero mineral distortion.',
      notes: 'Crisp Nordic Mineral · Glacier Crisp',
      swatchHex: '#e8edf2',
      accentHex: '#d8eefc',
      glassColor: 0xffffff,
      attenuationColor: 0xe0f2fe,
      attenuationDistance: 4.2,
      liquidColor: 0xedf7fc,
      liquidOpacity: 0.55,
      capColor: 0x383a42,
      capMetalness: 0.92,
      capRoughness: 0.24,
      haloColor: 0xc9a876,
      price: 68,
    },
    {
      id: 'rose',
      name: 'AURA Rose',
      subtitle: 'Soft Smoky Blush Glass',
      tag: 'Limited Studio Batch',
      description: 'Infused with trace mineral oxides during the melt cycle, casting a warm dawn blush that catches morning sunlight through architectural facets.',
      notes: 'Wild Briar · White Cedar · Mineral Blush',
      swatchHex: '#e4a5ad',
      accentHex: '#f0b8c0',
      glassColor: 0xfff0f2,
      attenuationColor: 0xfcc7cf,
      attenuationDistance: 3.4,
      liquidColor: 0xffebf0,
      liquidOpacity: 0.60,
      capColor: 0xd8a29e,
      capMetalness: 0.88,
      capRoughness: 0.22,
      haloColor: 0xe0989f,
      price: 78,
    },
    {
      id: 'amber',
      name: 'AURA Amber',
      subtitle: 'Warm Honey Glass',
      tag: 'Reserve Series',
      description: 'Deep cognac tones reminiscent of Baltic amber and aged resins. The thick crystal punt base refracts amber halos across wooden tabletops.',
      notes: 'Sun-Warmed Resin · Golden Honey · Tonka',
      swatchHex: '#d99748',
      accentHex: '#e8a858',
      glassColor: 0xfff6ea,
      attenuationColor: 0xfad69b,
      attenuationDistance: 3.2,
      liquidColor: 0xfff3db,
      liquidOpacity: 0.58,
      capColor: 0xc8924e,
      capMetalness: 0.90,
      capRoughness: 0.22,
      haloColor: 0xe8a048,
      price: 78,
    },
    {
      id: 'midnight',
      name: 'AURA Midnight',
      subtitle: 'Smoked Obsidian Glass',
      tag: 'Architectural Edition',
      description: 'A discreet smoked quartz tint that absorbs harsh glare while revealing fluid motion in silhouette. Finished with a gunmetal ceramic-bonded cap.',
      notes: 'Smoked Vetiver · Wet River Stone · Black Pepper',
      swatchHex: '#343642',
      accentHex: '#64687d',
      glassColor: 0xdee3eb,
      attenuationColor: 0x5a6078,
      attenuationDistance: 2.8,
      liquidColor: 0x363d4e,
      liquidOpacity: 0.70,
      capColor: 0x424654,
      capMetalness: 0.94,
      capRoughness: 0.20,
      haloColor: 0x5e688a,
      price: 84,
    },
    {
      id: 'pearl',
      name: 'AURA Pearl',
      subtitle: 'Soft Opaline Satin Glass',
      tag: 'Atelier Series',
      description: 'Micro-etched with an acid-washed opalescent silk finish. Softens ambient reflections into a luminous, diffused cloud-like aura in hand.',
      notes: 'Silk Blossom · Crushed Salt · Sweet Iris',
      swatchHex: '#f0ece3',
      accentHex: '#f8f4ec',
      glassColor: 0xfcfaf6,
      attenuationColor: 0xf5efe6,
      attenuationDistance: 3.6,
      liquidColor: 0xfcf9f2,
      liquidOpacity: 0.65,
      capColor: 0xd6c4a5,
      capMetalness: 0.85,
      capRoughness: 0.28,
      haloColor: 0xd8c8ab,
      price: 84,
    },
    {
      id: 'emerald',
      name: 'AURA Emerald',
      subtitle: 'Deep Nordic Forest Glass',
      tag: 'Nordic Heritage',
      description: 'Inspired by ancient apothecary carboys and pine canopies along the Danish coastline. Casts rich moss reflections under natural raking light.',
      notes: 'Fir Needle · Deep Pine · Coastal Rain Moss',
      swatchHex: '#265442',
      accentHex: '#3a785f',
      glassColor: 0xedf7f2,
      attenuationColor: 0x5ba887,
      attenuationDistance: 3.0,
      liquidColor: 0xd2ede0,
      liquidOpacity: 0.62,
      capColor: 0x486b59,
      capMetalness: 0.90,
      capRoughness: 0.22,
      haloColor: 0x3d7e63,
      price: 88,
    },
  ],
};

export function findSize(id) {
  return PRODUCT.sizes.find((s) => s.id === id) || PRODUCT.sizes[0];
}

export function findFinish(id) {
  return PRODUCT.finishes.find((f) => f.id === id) || PRODUCT.finishes[0];
}

export function findVariant(id) {
  return PRODUCT.collection.find((c) => c.id === id) || PRODUCT.collection[0];
}
